# Generated by Django 6.0.2 on 2026-03-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticket',
            field=models.CharField(default='NULL', max_length=4),
        ),
    ]
