# Generated by Django 6.0.2 on 2026-03-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
